services:
  "{{STACK_NAME}}":
    image: appsmith/appsmith-ee
    volumes:
      - "{{APPSMITH_STORAGE}}:/appsmith-stacks"
    expose:
      - "80/http/Appsmith Dashboard"
docs:
  logo_url: "https://raw.githubusercontent.com/swiftwave-org/app-store/main/assets/logos/appsmith.png"
  name: "Appsmith"
  description: "Open-Source Internal Tool Builder"
  readme_description: >
    ### What is Appsmith?

    Organizations build internal applications such as dashboards, database GUIs, admin panels, approval apps, customer support tools, etc. to help improve their business operations. Appsmith is an open-source developer tool that enables the rapid development of these applications. You can drag and drop pre-built widgets to build UI. Connect securely to your databases & APIs using its datasources. Write business logic to read & write data using queries & JavaScript.

    ### Why Appsmith

    Appsmith makes it easy to build a UI that talks to any datasource. You can create anything from simple CRUD apps to complicated multi-step workflows with a few simple steps:

    - Connect Datasource: Integrate with a database or API. Appsmith supports the most popular databases and REST APIs.

    - Build UI: Use built-in widgets to build your app layout.

    - Write Logic: Express your business logic using queries and JavaScript anywhere in the editor.

    - Collaborate, Deploy, Share: Appsmith supports version control using Git to build apps in collaboration using branches to track and roll back changes. Deploy the app and share it with other users.

    ### Note

    - Your server should have Two Virtual CPU and 4GB of RAM for optimal performance.

    - For first time, appsmith can take upto 10 minutes to start. Take look at the **Runtime Log** to see the progress.

    ### Links

    - Official Wesbite - [appsmith.com](https://appsmith.com)

    - Github - [github.com/appsmithorg/appsmith](https://github.com/appsmithorg/appsmith)

  iframe_video_embed: ""
  variables:
    APPSMITH_STORAGE:
      title: "Appsmith Storage"
      description: "The storage location for appsmith"
      default: ""
      type: volume
      options:
