services:
  "{{STACK_NAME}}_frontend":
    image: penpotapp/frontend:latest
    environment:
      - "PENPOT_FLAGS={{ALLOW_USER_REGISTRATION}} enable-login-with-password"
      - "PENPOT_BACKEND_URI=http://{{STACK_NAME}}_backend:6060"
      - "PENPOT_EXPORTER_URI=http://{{STACK_NAME}}_exporter:6061"
    volumes:
      - "{{ASSETS_STORAGE}}:/opt/data/assets"
    expose:
      - "80/http/Penpot Endpoint"

  "{{STACK_NAME}}_backend":
    image: penpotapp/backend:latest
    environment:
      - "PENPOT_BACKEND_URI=http://{{STACK_NAME}}_backend:6060"
      - "PENPOT_EXPORTER_URI=http://{{STACK_NAME}}_exporter:6061"
      - "PENPOT_FLAGS={{ALLOW_USER_REGISTRATION}} enable-login-with-password disable-email-verification enable-prepl-server"
      - "PENPOT_PUBLIC_URI={{PUBLIC_URL}}"
      - "PENPOT_DATABASE_URI=postgresql://{{STACK_NAME}}_db/penpot"
      - "PENPOT_DATABASE_USERNAME=penpot"
      - "PENPOT_DATABASE_PASSWORD={{RANDOM_POSTGRES_PASSWORD}}"
      - "PENPOT_REDIS_URI=redis://{{STACK_NAME}}_redis/0"
      - "PENPOT_ASSETS_STORAGE_BACKEND=assets-fs"
      - "PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets"
      - "PENPOT_TELEMETRY_ENABLED=false"
    volumes:
      - "{{ASSETS_STORAGE}}:/opt/data/assets"


  "{{STACK_NAME}}_exporter":
    image: penpotapp/exporter:latest
    environment:
      - "PENPOT_PUBLIC_URI=http://{{STACK_NAME}}_frontend"
      - "PENPOT_REDIS_URI=redis://{{STACK_NAME}}_redis/0"
  
  "{{STACK_NAME}}_db":
    image: postgres:15
    environment:
      - "POSTGRES_INITDB_ARGS=--data-checksums"
      - "POSTGRES_DB=penpot"
      - "POSTGRES_USER=penpot"
      - "POSTGRES_PASSWORD={{RANDOM_POSTGRES_PASSWORD}}"
    volumes:
      - "{{POSTGRES_STORAGE}}:/var/lib/postgresql/data"

  "{{STACK_NAME}}_redis":
    image: redis:7
docs:
  logo_url: "https://raw.githubusercontent.com/swiftwave-org/app-store/main/assets/logos/penpot.png"
  name: "Penpot"
  description: "The open-source design tool for design and code collaboration"
  readme_description: >
    ### What is Penpot ?

    Penpot is the first open-source design tool for design and code collaboration. Designers can create stunning designs, interactive prototypes, design systems at scale, while developers enjoy ready-to-use code and make their workflow easy and fast. And all of this with no handoff drama.

    ### Links

    - Official Wesbite - [penpot.app](https://penpot.app/)

    - GitHub - [github.com/penpot/penpot](https://github.com/penpot/penpot)

  iframe_video_embed: ""
  variables:
    ALLOW_USER_REGISTRATION:
      title: "Allow user registration"
      description: "If enabled, users can register for Penpot"
      default: "enable-registration"
      type: options
      options:
        - title: Enable
          value: "enable-registration"
        - title: Disable
          value: "disable-registration"
    PUBLIC_URL:
      title: "Public URL for Penpot"
      description: "i.e. https://example.com"
      default: ""
      type: text
      options:
    ASSETS_STORAGE:
      title: "Assets Storage"
      description: "The storage location for Penpot assets"
      default: ""
      type: volume
      options:
    POSTGRES_STORAGE:
      title: "Database Data Storage"
      description: "The data storage for Postgres DB"
      default: ""
      type: volume
      options:
