services:
  "{{STACK_NAME}}_frontend":
    image: penpotapp/frontend:latest
    environment:
      - "PENPOT_FLAGS={{ALLOW_USER_REGISTRATION}} enable-login-with-password"
      - "PENPOT_BACKEND_URI=http://{{STACK_NAME}}_backend:6060"
      - "PENPOT_EXPORTER_URI=http://{{STACK_NAME}}_exporter:6061"
    volumes:
      - "{{ASSETS_STORAGE}}:/opt/data/assets"
    expose:
      - "80/http/Penpot Endpoint"
    preferred_server_hostnames:
      - "{{DEPLOYMENT_SERVER}}"

  "{{STACK_NAME}}_backend":
    image: penpotapp/backend:latest
    environment:
      - "PENPOT_BACKEND_URI=http://{{STACK_NAME}}_backend:6060"
      - "PENPOT_EXPORTER_URI=http://{{STACK_NAME}}_exporter:6061"
      - "PENPOT_FLAGS={{ALLOW_USER_REGISTRATION}} enable-login-with-password enable-smtp {{EMAIL_VERIFICATION}} enable-prepl-server"
      - "PENPOT_PUBLIC_URI={{PUBLIC_URL}}"
      - "PENPOT_DATABASE_URI=postgresql://{{STACK_NAME}}_db/penpot"
      - "PENPOT_DATABASE_USERNAME=penpot"
      - "PENPOT_DATABASE_PASSWORD={{RANDOM_POSTGRES_PASSWORD}}"
      - "PENPOT_REDIS_URI=redis://{{STACK_NAME}}_redis/0"
      - "PENPOT_ASSETS_STORAGE_BACKEND=assets-fs"
      - "PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets"
      - "PENPOT_TELEMETRY_ENABLED=false"
      - "PENPOT_SMTP_DEFAULT_FROM={{DEFAULT_FROM_EMAIL}}"
      - "PENPOT_SMTP_DEFAULT_REPLY_TO={{DEFAULT_REPLY_TO_EMAIL}}"
      - "PENPOT_SMTP_HOST={{SMTP_HOST}}"
      - "PENPOT_SMTP_PORT={{SMTP_PORT}}"
      - "PENPOT_SMTP_USERNAME={{SMTP_USERNAME}}"
      - "PENPOT_SMTP_PASSWORD={{SMTP_PASSWORD}}"
      - "PENPOT_SMTP_TLS={{SMTP_TLS_MODE}}"
      - "PENPOT_SMTP_SSL={{SMTP_SSL_MODE}}"
    volumes:
      - "{{ASSETS_STORAGE}}:/opt/data/assets"
    preferred_server_hostnames:
      - "{{DEPLOYMENT_SERVER}}"

  "{{STACK_NAME}}_exporter":
    image: penpotapp/exporter:latest
    environment:
      - "PENPOT_PUBLIC_URI=http://{{STACK_NAME}}_frontend"
      - "PENPOT_REDIS_URI=redis://{{STACK_NAME}}_redis/0"
    preferred_server_hostnames:
      - "{{DEPLOYMENT_SERVER}}"

  "{{STACK_NAME}}_db":
    image: postgres:15
    environment:
      - "POSTGRES_INITDB_ARGS=--data-checksums"
      - "POSTGRES_DB=penpot"
      - "POSTGRES_USER=penpot"
      - "POSTGRES_PASSWORD={{RANDOM_POSTGRES_PASSWORD}}"
    volumes:
      - "{{POSTGRES_STORAGE}}:/var/lib/postgresql/data"
    preferred_server_hostnames:
      - "{{DEPLOYMENT_SERVER}}"

  "{{STACK_NAME}}_redis":
    image: redis:7
    preferred_server_hostnames:
      - "{{DEPLOYMENT_SERVER}}"
docs:
  logo_url: "https://raw.githubusercontent.com/swiftwave-org/app-store/main/assets/logos/penpot.png"
  name: "Penpot"
  description: "The open-source design tool for design and code collaboration"
  readme_description: >
    ### What is Penpot ?

    Penpot is the first open-source design tool for design and code collaboration. Designers can create stunning designs, interactive prototypes, design systems at scale, while developers enjoy ready-to-use code and make their workflow easy and fast. And all of this with no handoff drama.

    ### Links

    - Official Wesbite - [penpot.app](https://penpot.app/)

    - GitHub - [github.com/penpot/penpot](https://github.com/penpot/penpot)

  iframe_video_embed: ""
  variables:
    DEPLOYMENT_SERVER:
      title: "Deployment Server"
      description: "The server to deploy penpot"
      default: ""
      type: server
      options:
    PUBLIC_URL:
      title: "Public URL for Penpot"
      description: "i.e. https://example.com"
      default: ""
      type: text
      options:
    ALLOW_USER_REGISTRATION:
      title: "Allow user registration"
      description: "If enabled, users can register for Penpot"
      default: "enable-registration"
      type: options
      options:
        - title: Enable
          value: "enable-registration"
        - title: Disable
          value: "disable-registration"
    EMAIL_VERIFICATION:
      title: "Email verification"
      description: "If enabled, users will be required to verify their email address"
      default: "enable-email-verification"
      type: options
      options:
        - title: Enable
          value: "enable-email-verification"
        - title: Disable
          value: "disable-email-verification"
    SMTP_HOST:
      title: "SMTP Host"
      description: "i.e. smtp.google.com"
      default: ""
      type: text
      options:
    SMTP_PORT:
      title: "SMTP Port"
      description: "i.e. 25,465,587,2525"
      default: "587"
      type: text
      options:
    SMTP_USERNAME:
      title: "SMTP Username"
      description: "i.e. example@gmail.com"
      default: ""
      type: text
      options:
    SMTP_PASSWORD:
      title: "SMTP Password"
      description: "i.e. password"
      default: ""
      type: text
      options:
    SMTP_SSL_MODE:
      title: "SMTP SSL Mode"
      description: "For connecting to SMTP server over SSL"
      default: "false"
      type: options
      options:
        - title: Enable
          value: "true"
        - title: Disable
          value: "false"
    SMTP_TLS_MODE:
      title: "SMTP TLS Mode"
      description: "For connecting to SMTP server over TLS"
      default: "true"
      type: options
      options:
        - title: Enable
          value: "true"
        - title: Disable
          value: "false"
    DEFAULT_FROM_EMAIL:
      title: "Default From Email"
      description: "i.e. no-reply@example.com"
      default: "no-reply@example.com"
      type: text
      options:
    DEFAULT_REPLY_TO_EMAIL:
      title: "Default Reply To Email"
      description: "i.e. no-reply@example.com"
      default: "no-reply@example.com"
      type: text
      options:
    ASSETS_STORAGE:
      title: "Assets Storage"
      description: "The storage location for Penpot assets"
      default: ""
      type: volume
      options:
    POSTGRES_STORAGE:
      title: "Database Data Storage"
      description: "The data storage for Postgres DB"
      default: ""
      type: volume
      options:
